---
- hosts: all
  sudo: yes
  tasks:
  - name: install abc
    apt: name={{item}} state=latest update_cache=yes
    with_items:
     - apache2
     - libapache2-mod-wsgi
     - python-pip
     - python-virtualenv
